# Generated by Django 4.2.1 on 2023-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_userbio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbio",
            name="avatar",
            field=models.ImageField(
                default="avatar.svg", null=True, upload_to="images/studybud"
            ),
        ),
    ]
