# Generated by Django 4.2.2 on 2023-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todowork",
            name="is_due",
            field=models.BooleanField(default=False),
        ),
    ]
