# Generated by Django 4.2.1 on 2023-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
