# Generated by Django 4.1.7 on 2023-05-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AITextAssist", "0002_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(
                blank=True, default="chat", max_length=200, null=True
            ),
        ),
    ]
