# Generated by Django 4.1.7 on 2023-05-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AITextAssist", "0003_message_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="type", new_name="msgtype",
        ),
    ]
